# test_attacker.py — Unit tests for the Byzantine attack simulation.
#
# Tests to implement:
#
#   class TestLabelFlipping:
#       def test_only_target_class_is_flipped(): ...
#       def test_non_target_labels_untouched(): ...
#       def test_flipped_count_matches_expected(): ...
#
#   class TestBackdoorInjection:
#       def test_trigger_features_have_exact_values(): ...
#       def test_injected_samples_labeled_benign(): ...
#       def test_inject_ratio_produces_correct_count(): ...
#       def test_original_data_not_modified(): ...
#
#   class TestGradientScaling:
#       def test_scaled_norm_matches_target(): ...
#       def test_direction_preserved_after_scaling(): ...
