# test_aggregator.py — Unit tests for the 3-part defense pipeline math.
#
# Tests to implement:
#
#   class TestCosineSimlarity:
#       def test_identical_vectors_return_similarity_1(): ...
#       def test_orthogonal_vectors_return_similarity_0(): ...
#       def test_final_layer_extraction_shape(): ...
#       def test_similarity_matrix_is_symmetric(): ...
#
#   class TestMADScoring:
#       def test_all_identical_scores_mad_is_zero(): ...
#       def test_single_outlier_is_flagged(): ...
#       def test_division_by_zero_protection(): ...
#       def test_threshold_tau_sensitivity(): ...
#
#   class TestCappedSimplexProjection:
#       def test_output_sums_to_one(): ...
#       def test_no_weight_exceeds_cap(): ...
#       def test_negative_scores_get_zero_weight(): ...
#       def test_all_equal_scores_give_uniform_weights(): ...
#       def test_output_shape_matches_input(): ...
#
#   class TestEMATrustScoring:
#       def test_initial_reputation_is_neutral(): ...
#       def test_persistent_attacker_score_decays(): ...
#       def test_recovering_client_score_increases(): ...
#       def test_temperature_softmax_sums_to_one(): ...
#       def test_numerically_stable_softmax_no_overflow(): ...
