# test_data_partitioner.py — Unit tests for IID and Non-IID data partitioning.
#
# Tests to implement:
#
#   class TestIIDPartition:
#       def test_all_clients_receive_data(): ...
#       def test_total_samples_preserved(): ...
#       def test_class_distribution_roughly_uniform(): ...
#
#   class TestNonIIDPartition:
#       def test_all_clients_receive_data(): ...
#       def test_total_samples_preserved(): ...
#       def test_low_alpha_creates_heterogeneous_splits(): ...
#       def test_high_alpha_approximates_iid(): ...
#       def test_output_shapes_correct(): ...
#
#   class TestPreprocessing:
#       def test_z_score_normalization_mean_near_zero(): ...
#       def test_z_score_normalization_std_near_one(): ...
#       def test_feature_count_after_variance_filter(): ...
#       def test_no_nan_values_after_preprocessing(): ...
